# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoist < Formula
  desc "Todoist CLI client"
  homepage "https://github.com/sachaos/todoist"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/todoist/releases/download/v0.21.0/todoist_Darwin_x86_64.tar.gz"
      sha256 "01d105680aba7a3bd3bb2313ed7fe4c1c4df62582fad0bf19ba82ef95a26a80d"

      def install
        bin.install "todoist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sachaos/todoist/releases/download/v0.21.0/todoist_Darwin_arm64.tar.gz"
      sha256 "175db7a3c448b3c684bb83fb75e98e2988b210e9b16e626651b693d7c44e7d23"

      def install
        bin.install "todoist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sachaos/todoist/releases/download/v0.21.0/todoist_Linux_x86_64.tar.gz"
        sha256 "227c196568f166d85017070e22aabad1e05d65e2df0e8af799f43f35125f0798"

        def install
          bin.install "todoist"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sachaos/todoist/releases/download/v0.21.0/todoist_Linux_armv6.tar.gz"
        sha256 "c396d5c40c87adfca4e66cea614f1f93c47bcdef99b66bea564960a596b36b75"

        def install
          bin.install "todoist"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sachaos/todoist/releases/download/v0.21.0/todoist_Linux_arm64.tar.gz"
        sha256 "65581e4447da78fcea0e3c3c6fc3710943e6fd5edf7e231a5a9f9265ced346a7"

        def install
          bin.install "todoist"
        end
      end
    end
  end
end
